### ISSUE TITLE
如果将路径指定public那么该怎么做？

### ISSUE THREAD

**Issue by Mirdoriss** [klren0312/vite_vue2.7#1]
放置public/index.html作为打包入口，要安装插件吗？

**Comment by Mirdoriss** [comment]
![图片](https://user-images.githubusercontent.com/35458322/187821185-9c414f38-c450-4cfa-887e-b107a83fdb33.png)
打包报错了

**Comment by klren0312** [comment]
安装下terser, 我删错了

**Comment by klren0312** [comment]
> 放置public/index.html作为打包入口，要安装插件吗？

https://www.vitejs.net/guide/#index-html-and-project-root

![图片](https://user-images.githubusercontent.com/10903843/187823025-e8f47976-28be-4403-bd71-56f863e1c9b2.png)
