### ISSUE TITLE
css v-bind在build之后无效

### ISSUE THREAD

**Issue by hxgqh** [klren0312/vite_vue2.7#2]
1. npm run build
2. 发布dist/到nginx
3. 查看带 css v-bind的页面

**Comment by klren0312** [comment]
你可以提个pr看看咋解决吗

**Comment by hxgqh** [comment]
> 你可以提个pr看看咋解决吗

好的，稍等，我提一个

**Comment by klren0312** [comment]
感谢

**Comment by hxgqh** [comment]
已提。https://github.com/klren0312/vite_vue2.7/pull/3
访问地址：http://localhost:28847/#/TestVbind
