### ISSUE TITLE
hello  大佬请教个问题，我使用vue2.7.14的时候使用onMounted会报错。

### ISSUE THREAD

**Issue by xiaoxiaohuayu** [klren0312/vite_vue2.7#4]
`onMounted is called when there is no active component instance to be associated with. Lifecycle injection APIs can only be used during execution of setup().
这个您知道怎么解决吗

**Comment by klren0312** [comment]
看你具体代码 是不是<script> 标签里没放setup
<script setup>

**Comment by klren0312** [comment]
我这边更新成了vue2.7.14 测试正常

**Comment by xiaoxiaohuayu** [comment]
> 我这边更新成了vue2.7.14 测试正常

可以了。多引入了一个插件

**Comment by klren0312** [comment]
> > 我这边更新成了vue2.7.14 测试正常
> 
> 可以了。多引入了一个插件

收到
