### ISSUE TITLE
一开始我以为是一个好的基础框架，但是在chrome63和chrome69上有报错

### ISSUE THREAD

**Issue by qew4** [klren0312/vite_vue2.7#5]
一开始我以为是一个好的基础框架，可以兼容到IE11，但是在chrome63和chrome69上有报错，chrome63我认为比ie11还要优秀的版本。

**Comment by klren0312** [comment]
有什么报错列出来 大家一起解决

**Comment by klren0312** [comment]
### chrome63报错
![image](https://github.com/klren0312/vite_vue2.7/assets/10903843/e6fe3f8a-39b7-4588-b122-e1d833241a8e)

**Comment by klren0312** [comment]
看的像vue的问题啊 你小子, 报错第五行有问题, 第五行是vue的源码部分
![image](https://github.com/klren0312/vite_vue2.7/assets/10903843/3e4d2096-c8a3-41ed-8e29-2ba737a3cb25)
![1702367510600](https://github.com/klren0312/vite_vue2.7/assets/10903843/ba9dac52-e385-4276-b6c2-06ed9332678b)

**Comment by qew4** [comment]
![error1](https://github.com/klren0312/vite_vue2.7/assets/16102992/738b3fa1-e285-461c-b4bd-7d7055a5008e)

**Comment by klren0312** [comment]
> ![error1](https://private-user-images.githubusercontent.com/16102992/289796912-738b3fa1-e285-461c-b4bd-7d7055a5008e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI0NTU2OTYsIm5iZiI6MTcwMjQ1NTM5NiwicGF0aCI6Ii8xNjEwMjk5Mi8yODk3OTY5MTItNzM4YjNmYTEtZTI4NS00NjFjLWI0YmQtN2Q3MDU1YTUwMDhlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEzVDA4MTYzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTczYmE3ZjFmMmM4YjQ4N2VhZWY4MzM1NjhjYzkwYzlkODk2MGZmNmQwMGIyMWQ0Mjc4N2ZlYTBiNDAxYTYzNjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.t1kFWUh2VXkEFN0xjw9Powk4HtKuo7nZnWICuk1nDzA)

你觉得是什么问题呢

**Comment by klren0312** [comment]
@qew4 69可正常访问了

![1703819905024](https://github.com/klren0312/vite_vue2.7/assets/10903843/f523b7c6-6269-40c3-96b1-982bb4b3c034)
