### ISSUE TITLE
自动按需加载的elementUI, 同类名样式无法被覆盖

### ISSUE THREAD

**Issue by wangermaizi** [klren0312/vite_vue2.7#6]
在`vite.config.js`配置按需引入之后
`Components({
    resolvers: [ElementUiResolver()],
  }),`

在main.ts引入自己写的样式时
相同类名的 .el-button 样式无法覆盖 elementUI自身的样式

疑似是在编译时将elementUI样式编译在header标签的后面, 请问作者有遇到这个问题吗?

**Comment by klren0312** [comment]
用`!important`覆盖
![1709602943167](https://github.com/klren0312/vite_vue2.7/assets/10903843/7ed748a9-80ec-47e3-9e90-db56359f3f39)
![1709602983904](https://github.com/klren0312/vite_vue2.7/assets/10903843/4a1547c9-32f9-4012-b0ce-7907c86864b2)
