### ISSUE TITLE
打包案例部署服务发现Uncaught TypeError: Cannot set properties of undefined (setting 'exports')

### ISSUE THREAD

**Issue by wangermaizi** [klren0312/vite_vue2.7#7]
打包部署服务器时修改了 `vite.config.js` 中的base值
![image](https://github.com/klren0312/vite_vue2.7/assets/55691571/84c35077-19cb-4693-9886-bfad2d870d46)
部署之后页面提示错误: 
![image](https://github.com/klren0312/vite_vue2.7/assets/55691571/bad6b236-51a9-41c3-b360-d13c13cc9b36)
我翻了一下项目都找不到cjs导出代码

请问作者有遇到这个问题吗

**Comment by klren0312** [comment]
看了下是打包分割导致的 先去掉了 可以把`vite.config.ts`红色区域删除
![image](https://github.com/klren0312/vite_vue2.7/assets/10903843/729373e9-4608-431b-98af-6dd1b84bbafc)
