### ISSUE TITLE
node版本多少啊，安装包报错

### ISSUE THREAD

**Issue by zhongfeixu** [klren0312/vite_vue2.7#8]
![image](https://github.com/klren0312/vite_vue2.7/assets/29174767/506c5f0a-61d8-4f0d-8392-0287628c4107)

**Comment by zhongfeixu** [comment]
这个是node18的报错
![image](https://github.com/klren0312/vite_vue2.7/assets/29174767/2d8117ac-76b3-47bf-a6f7-9c4a55e1383b)

**Comment by klren0312** [comment]
node20 + pnpm

**Comment by klren0312** [comment]
有问题再开启吧
